/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "pipeline_reg.sv:1.1-42.10" *)
module pipeline_reg(clk, rst_n, in_data, in_valid, in_ready, out_data, out_valid, out_ready);
  (* src = "pipeline_reg.sv:4.36-4.39" *)
  input clk;
  wire clk;
  (* src = "pipeline_reg.sv:5.36-5.41" *)
  input rst_n;
  wire rst_n;
  (* src = "pipeline_reg.sv:8.36-8.43" *)
  input [31:0] in_data;
  wire [31:0] in_data;
  (* src = "pipeline_reg.sv:9.36-9.44" *)
  input in_valid;
  wire in_valid;
  (* src = "pipeline_reg.sv:10.36-10.44" *)
  output in_ready;
  wire in_ready;
  (* src = "pipeline_reg.sv:13.36-13.44" *)
  output [31:0] out_data;
  wire [31:0] out_data;
  (* src = "pipeline_reg.sv:14.36-14.45" *)
  output out_valid;
  wire out_valid;
  (* src = "pipeline_reg.sv:15.36-15.45" *)
  input out_ready;
  wire out_ready;
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "pipeline_reg.sv:10.36-10.44" *)
  wire _06_;
  (* src = "pipeline_reg.sv:9.36-9.44" *)
  wire _07_;
  (* src = "pipeline_reg.sv:15.36-15.45" *)
  wire _08_;
  (* src = "pipeline_reg.sv:5.36-5.41" *)
  wire _09_;
  (* src = "pipeline_reg.sv:19.28-19.37" *)
  wire _10_;
  (* src = "pipeline_reg.sv:18.28-18.36" *)
  reg [31:0] data_reg;
  (* src = "pipeline_reg.sv:19.28-19.37" *)
  reg valid_reg;
  assign _06_ = _08_ | ~(_10_);
  assign _03_ = _07_ & _06_;
  assign _05_ = _09_ & _03_;
  assign _04_ = _10_ ? _08_ : _07_;
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) valid_reg <= 1'h0;
    else if (_01_) valid_reg <= _00_;
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[0] <= in_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[1] <= in_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[2] <= in_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[3] <= in_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[4] <= in_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[5] <= in_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[6] <= in_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[7] <= in_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[8] <= in_data[8];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[9] <= in_data[9];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[10] <= in_data[10];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[11] <= in_data[11];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[12] <= in_data[12];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[13] <= in_data[13];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[14] <= in_data[14];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[15] <= in_data[15];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[16] <= in_data[16];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[17] <= in_data[17];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[18] <= in_data[18];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[19] <= in_data[19];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[20] <= in_data[20];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[21] <= in_data[21];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[22] <= in_data[22];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[23] <= in_data[23];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[24] <= in_data[24];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[25] <= in_data[25];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[26] <= in_data[26];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[27] <= in_data[27];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[28] <= in_data[28];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[29] <= in_data[29];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[30] <= in_data[30];
  (* \always_ff  = 32'd1 *)
  (* src = "pipeline_reg.sv:26.5-40.8" *)
  always @(posedge clk)
    if (_02_) data_reg[31] <= in_data[31];
  assign out_data = data_reg;
  assign out_valid = valid_reg;
  assign _08_ = out_ready;
  assign _10_ = valid_reg;
  assign in_ready = _06_;
  assign _07_ = in_valid;
  assign _00_ = _03_;
  assign _09_ = rst_n;
  assign _02_ = _05_;
  assign _01_ = _04_;
endmodule


